#!/usr/bin/env python3
"""Copy an investigation's Markdown records into its pages folder and generate its Sources page.

For every investigation in the registry (a government repository, or the hub after assemble.py):
  docs/<inv>/references.md         <- investigations/<inv>/REFERENCES.md
  docs/<inv>/audit-summary.md      <- investigations/<inv>/AUDIT_SUMMARY.md
  docs/<inv>/independent-review.md <- investigations/<inv>/<review>/INDEPENDENT_REVIEW_SUMMARY.md
  docs/<inv>/notes/*.md            <- investigations/<inv>/notes/*.md
  docs/<inv>/sources.md            <- every file of the investigation, with size, SHA-256 and a link to the repository
Relative file references in the copied documents become links to the files on GitHub, so every reference document is
reachable from the website.  --check exits 1 if the copies are out of date.
"""
import os, re, sys, glob
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from registry import Registry, find_root
R=Registry(find_root()); check='--check' in sys.argv; changed=[]
EXCLUDED=('sources/news','sources/analysis')            # not republished (copyright); left unlinked
def write(path,text):
    old=open(path).read() if os.path.exists(path) else None
    if old!=text:
        changed.append(os.path.relpath(path,R.root))
        if not check: os.makedirs(os.path.dirname(path),exist_ok=True); open(path,'w').write(text)
def human(n): return f'{n/1e6:.1f} MB' if n>=1e6 else f'{n/1e3:.0f} KB'
def sync(inv):
    INV,DOCS,REVIEW=inv['inv_dir'],inv['docs'],inv.get('review')
    BLOB=f"{inv['repo']}/blob/{inv['ref']}/investigations/{inv['rel']}"
    folders='data|sources|notes|scripts|charts|report'+(('|'+re.escape(REVIEW)) if REVIEW else '')
    PATH_RE=r'(?:'+folders+r')/[^`\s)\]]+|REFERENCES\.md|AUDIT_SUMMARY\.md|MANIFEST_SHA256\.txt|README\.md'
    def linkify(text,base=BLOB):
        def fix(t):
            if re.match(r'https?://|#|mailto:',t) or t.lstrip('./').startswith(EXCLUDED): return t
            return f'{base}/{t.lstrip("./")}'
        text=re.sub(r'\]\(([^)\s]+)\)',lambda m:'](' + fix(m.group(1)) + ')',text)
        text=re.sub(r'(?<!\]\()`('+PATH_RE+r')`',lambda m:m.group(0) if m.group(1).startswith(EXCLUDED) else f'[`{m.group(1)}`]({base}/{m.group(1)})',text)
        return text
    def header(src): return f'<!-- generated by tools/sync_docs.py from {src}; edit the source file, then re-run the tool -->\n'
    if os.path.exists(f'{INV}/REFERENCES.md'): write(f'{DOCS}/references.md',header('REFERENCES.md')+linkify(open(f'{INV}/REFERENCES.md').read()))
    if os.path.exists(f'{INV}/AUDIT_SUMMARY.md'): write(f'{DOCS}/audit-summary.md',header('AUDIT_SUMMARY.md')+linkify(open(f'{INV}/AUDIT_SUMMARY.md').read()))
    for n in sorted(glob.glob(f'{INV}/notes/*.md')):
        if os.path.basename(n)=='session_command_log.md': continue       # 480 KB; linked from the Sources page
        write(f'{DOCS}/notes/{os.path.basename(n)}',header(f'notes/{os.path.basename(n)}')+linkify(open(n).read()))
    if REVIEW and os.path.exists(f'{INV}/{REVIEW}/INDEPENDENT_REVIEW_SUMMARY.md'):
        s=open(f'{INV}/{REVIEW}/INDEPENDENT_REVIEW_SUMMARY.md').read()
        intro=(f'<!-- generated by tools/sync_docs.py from {REVIEW}/INDEPENDENT_REVIEW_SUMMARY.md -->\n'
               f'!!! note "About this page"\n    This is the summary of an independent review of revision 1 of the report, reproduced unchanged. '
               f'The full review package (findings and method, recalculation script, evidence downloads and its own checksum manifest) is in '
               f'[`{REVIEW}/`]({BLOB}/{REVIEW}). Revision 2 of the report adopted its corrections; see the [audit summary](audit-summary.md), Section 14.\n\n')
        write(f'{DOCS}/independent-review.md',intro+linkify(s,base=f'{BLOB}/{REVIEW}'))
    # Sources page
    hashes={}
    if os.path.exists(f'{INV}/MANIFEST_SHA256.txt'):
        for line in open(f'{INV}/MANIFEST_SHA256.txt'):
            h,_,p=line.rstrip('\n').partition('  '); hashes[p.lstrip('./')]=h
    titles={'sources/official':'Official documents (public records)','sources/city_of_houston':'City of Houston documents (pay, payroll, benefits, pensions, contracts)',
            'sources':'Source documents','data':'Data files derived from the documents (CSV/JSON) and text extractions','charts':'Charts',
            'report':'The archival report PDF','notes':'Notes, extracts, logs and the session command log','scripts':'Scripts'}
    if REVIEW: titles[REVIEW]='Independent review package'
    groups=[]
    if os.path.isdir(f'{INV}/sources'):
        subs=sorted(d for d in os.listdir(f'{INV}/sources') if os.path.isdir(f'{INV}/sources/{d}'))
        groups+=[(f'sources/{d}',titles.get(f'sources/{d}',f'Source documents: {d.replace("_"," ")}')) for d in subs]
    for f in ('data','charts','report','notes','scripts')+((REVIEW,) if REVIEW else ()):
        if os.path.isdir(f'{INV}/{f}'): groups.append((f,titles[f]))
    groups.append(('.','Top-level records'))
    out=['<!-- generated by tools/sync_docs.py; do not edit by hand -->','# Sources and files','',
         f'Every file behind the report, with its size and SHA-256 checksum. Links open the file in the repository <{inv["repo"]}> (PDFs open in the browser viewer; use the Download button there for a copy). '
         'What each document was used for is explained in [References](references.md). Checksums come from `MANIFEST_SHA256.txt`; verify a download with `sha256sum`.','',
         '!!! info "News articles"','    Full-page copies of the news articles and analysis pages that the report cites are held in the private working archive and are not republished, for copyright reasons. '
         'The facts taken from each article are in the notes (news extracts); every article\'s URL and retrieval date is in [References](references.md).','']
    total=0; count=0
    for folder,title in groups:
        base=INV if folder=='.' else f'{INV}/{folder}'; files=[]
        for dp,dn,fn in os.walk(base):
            if folder=='.': dn[:]=[]
            for f in fn:
                p=os.path.join(dp,f); files.append((os.path.relpath(p,INV),os.path.getsize(p)))
        files.sort()
        if not files: continue
        sub=sum(s for _,s in files); total+=sub; count+=len(files)
        out+=[f'## {title}',f'{len(files)} files, {human(sub)}.','']
        bulk=[f for f in files if '/classifications/' in f[0] and not f[0].endswith(('list_job_classifications_abc.pdf','list_job_classifications_123.pdf'))]
        main=[f for f in files if f not in bulk]
        def table(rows):
            t=['| File | Size | SHA-256 |','|---|---:|---|']
            for r_,sz in rows:
                h=hashes.get(r_,''); link=f'[{r_}]({BLOB}/{r_.replace(" ","%20")})'
                t.append(f'| {link} | {human(sz)} | `{h[:16]}…` |' if h else f'| {link} | {human(sz)} | |')
            return t
        out+=table(main)+['']
        if bulk: out+=[f'??? note "{len(bulk)} individual City of Houston job-description PDFs (one per job code; downloaded in bulk, not used for any figure)"','']+['    '+l for l in table(bulk)]+['']
    out+=[f'**Total: {count} files, {human(total)}.** The complete checksum list is [`MANIFEST_SHA256.txt`]({BLOB}/MANIFEST_SHA256.txt).']
    write(f'{DOCS}/sources.md','\n'.join(out)+'\n')
for inv in R.investigations: sync(inv)
if check and changed: print('OUT OF DATE (run sync_docs):',', '.join(changed)); sys.exit(1)
print(('synced: ' if changed else 'already current ')+', '.join(changed))
